export const ERC_6551_CTG_VAULT_ABI = [
    { type: 'receive', stateMutability: 'payable' },
    {
        type: 'function',
        name: 'CTG_TOKEN_CONTRACT',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'CTG_VOTING_START_TIMESTAMP',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'STAKERS_SHARE_PERCENTAGE',
        inputs: [],
        outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'WITHDRAWAL_ENABLED_TIMESTAMP',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'amountPerStaker',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'batchWithdraw',
        inputs: [],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'enableEarlyWithdrawals',
        inputs: [],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'execute',
        inputs: [
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'value', type: 'uint256', internalType: 'uint256' },
            { name: 'data', type: 'bytes', internalType: 'bytes' },
            { name: 'operation', type: 'uint8', internalType: 'uint8' },
        ],
        outputs: [{ name: 'result', type: 'bytes', internalType: 'bytes' }],
        stateMutability: 'payable',
    },
    {
        type: 'function',
        name: 'getStakedTokenIds',
        inputs: [{ name: 'staker', type: 'address', internalType: 'address' }],
        outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'implementation',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'isEarlyWithdrawalEnabled',
        inputs: [],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'isValidSignature',
        inputs: [
            { name: 'hash', type: 'bytes32', internalType: 'bytes32' },
            { name: 'signature', type: 'bytes', internalType: 'bytes' },
        ],
        outputs: [
            { name: 'magicValue', type: 'bytes4', internalType: 'bytes4' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'isValidSigner',
        inputs: [
            { name: 'signer', type: 'address', internalType: 'address' },
            { name: '', type: 'bytes', internalType: 'bytes' },
        ],
        outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'isWithdrawalEnabled',
        inputs: [],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'onERC721Received',
        inputs: [
            { name: '', type: 'address', internalType: 'address' },
            { name: 'from', type: 'address', internalType: 'address' },
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
            { name: '', type: 'bytes', internalType: 'bytes' },
        ],
        outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        name: 'owner',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'proxy',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'registry',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'selfOwnershipAccount',
        inputs: [],
        outputs: [{ name: '', type: 'address', internalType: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'state',
        inputs: [],
        outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'supportsInterface',
        inputs: [
            { name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' },
        ],
        outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        name: 'token',
        inputs: [],
        outputs: [
            { name: '', type: 'uint256', internalType: 'uint256' },
            { name: '', type: 'address', internalType: 'address' },
            { name: '', type: 'uint256', internalType: 'uint256' },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        name: 'withdraw',
        inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
        outputs: [],
        stateMutability: 'nonpayable',
    },
    { type: 'error', name: 'EnableWithdrawalsFailed', inputs: [] },
    {
        type: 'error',
        name: 'EnumerableMapNonexistentKey',
        inputs: [{ name: 'key', type: 'bytes32', internalType: 'bytes32' }],
    },
    { type: 'error', name: 'WithdrawalFailed', inputs: [] },
] as const;
